In [ ]:
# Retail Data – Business Questions (for `retail_data`)
**Assumed columns:** "[Store ID, Sales, Customers, Inventory, Returns]"


In [ ]:
import numpy as np
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

retail_data = np.array([
       [    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]
       ])
print(retail_data)

In [29]:
## Basic Performance Analysis
print("1. What is the **total revenue** generated across all stores?")
np.sum(retail_data[:,1]).item()


1. What is the **total revenue** generated across all stores?


335000

In [36]:
print("2. Which store recorded the **highest sales**?")
print(np.argmax(retail_data[:,1])+1)


2. Which store recorded the **highest sales**?
9


In [35]:
print("3. Which store recorded the **lowest sales**?")
print(np.argmin(retail_data[:,1])+1)

3. Which store recorded the **lowest sales**?
1


In [38]:
print("4. What is the **average daily sales** per store?")
print(np.mean(retail_data[:,1])/30)


4. What is the **average daily sales** per store?
1116.6666666666667


In [27]:
print("5. How many stores achieved sales **above ₹35,000**?")
np.sum(retail_data[:,1]>35000).item()


5. How many stores achieved sales **above ₹35,000**?


3

In [2]:
import numpy as np
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

retail_data = np.array([
       [    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]
       ])
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [4]:
## Customer Insights
print("6. Which store had the **highest customer footfall**?")
print(np.argmax(retail_data[:,1]/retail_data[:,2])+1)

6. Which store had the **highest customer footfall**?
1


In [16]:
print("7. What is the **average number of customers** per store?")
print(np.mean(retail_data[:,2]))


7. What is the **average number of customers** per store?
425.0


In [81]:
print("8. How many stores have **more than 450 customers**?")
print(np.sum(retail_data[:,2]>450))


8. How many stores have **more than 450 customers**?
3


In [82]:
print("9. Which store has the **lowest customer count**?")
print(np.argmin(retail_data[:,2])+1)


9. Which store has the **lowest customer count**?
1


In [104]:
print("10. Is there any store where **high sales do not correspond to high customers**?")

X=(np.argsort(retail_data[:,1]))
Y=(np.argsort(retail_data[:,2]))
print(X)
print(Y)
print("#"*100)
print(np.where(X!=Y)[0])


10. Is there any store where **high sales do not correspond to high customers**?
[0 5 2 7 1 9 4 6 3 8]
[0 5 2 7 9 4 1 6 3 8]
####################################################################################################
[4 5 6]


In [2]:
import numpy as np
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

retail_data = np.array([
       [    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]
       ])
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [77]:
## Inventory & Returns Analysis
print("11. What is the **total inventory** across all stores?")
print(np.sum(retail_data[:,3]))


11. What is the **total inventory** across all stores?
14300


In [9]:
print("12. Which store has the **highest inventory stock**?")
print(np.argmax(retail_data[:,3])+1)


12. Which store has the **highest inventory stock**?
9


In [90]:
print("13. How many stores have **inventory less than 1300 units**?")
print(np.sum(retail_data[:,3]<1300))


13. How many stores have **inventory less than 1300 units**?
3


In [100]:
print("14. Which store has the **highest return rate** (returns ÷ inventory)?")
print(np.argmax(retail_data[:,4]%retail_data[:,3])+1)


14. Which store has the **highest return rate** (returns ÷ inventory)?
9


In [5]:
print("15. Which stores have **returns greater than 15 units**?")
print(np.where(retail_data[:,4]>15)[0]+1)


15. Which stores have **returns greater than 15 units**?
[4 7 9]


In [4]:
import numpy as np
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

retail_data = np.array([
       [    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]
       ])
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [8]:
## Sales & Customer Correlation
print("16. Is there a **positive correlation** between sales and customers?")
P=np.corrcoef(retail_data[:,1], retail_data[:,2])[0,1]
print(P)
C=np.ceil(P)
if C==1:
    print(f"Strong positive correlation b/w sales and customers")
else:
    print("No correlation")

16. Is there a **positive correlation** between sales and customers?
0.9593636912502479
Strong positive correlation b/w sales and customers


In [17]:
print(":17. Which store has **high customer visits but low sales**?")
X=(retail_data[:,2]).mean()
Y=(retail_data[:,1]).mean()
Z=(retail_data[:,2]>X)&(retail_data[:,1]<Y)
R=np.where(Z)[0]
print(R)
 

:17. Which store has **high customer visits but low sales**?
[1]


In [18]:
print("18. Which store has **low customers but high sales**?")
X=(retail_data[:,2]).mean()
Y=(retail_data[:,1]).mean()
Z=(retail_data[:,2]<X)&(retail_data[:,1]>Y)
R=np.where(Z)[0]
print(R)
 


18. Which store has **low customers but high sales**?
[4]


In [19]:
print("19. How many stores have **sales per customer above ₹90**?")
X=(retail_data[:,1])
Y=(retail_data[:,2])
Z=np.sum((X/Y)>90)
print(Z)


19. How many stores have **sales per customer above ₹90**?
0


In [20]:
print("20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?")

X=(retail_data[:,2]).mean()
Y=(retail_data[:,3]).mean()
Z=(retail_data[:,2]<X)&(retail_data[:,3]>Y)
R=np.where(Z)[0]
print(R)
 

20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
[9]


In [21]:
import numpy as np
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

retail_data = np.array([
       [    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]
       ])
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [10]:

## Profitability & Growth
print("21. If profit margin is **20% of sales**, what is the **profit per store**?")
profit= 0.20*retail_data[:,1]
profit_per_store=np.column_stack((retail_data[:,0] , profit))
print(profit_per_store.astype(int))

21. If profit margin is **20% of sales**, what is the **profit per store**?
[[   1 5000]
 [   2 6400]
 [   3 5600]
 [   4 8200]
 [   5 7000]
 [   6 5400]
 [   7 7800]
 [   8 6000]
 [   9 9000]
 [  10 6600]]


In [48]:

print("22. Which store has the **highest profit**?")
X=retail_data[:,1]
y=retail_data[:,3]
Z=retail_data[:,4]
profit=X-(Y+Z)
print(np.argmax(profit)+1)


22. Which store has the **highest profit**?
9


In [50]:
print("23. Which store has the **lowest profit**?")
X=retail_data[:,1]
y=retail_data[:,3]
Z=retail_data[:,4]
profit=X-(Y+Z)
print(np.argmin(profit)+1)

23. Which store has the **lowest profit**?
1


In [55]:
print("24. If sales increase by **10% next month**, what are the **new sales figures**?")
X=retail_data[:,1]
Y=0.10*X
new_sales_figures=np.column_stack((retail_data[:,0] , Y))
print(new_sales_figures.astype(int))



24. If sales increase by **10% next month**, what are the **new sales figures**?
[[   1 2500]
 [   2 3200]
 [   3 2800]
 [   4 4100]
 [   5 3500]
 [   6 2700]
 [   7 3900]
 [   8 3000]
 [   9 4500]
 [  10 3300]]


In [66]:
print("25. How will **total profit** change with the 10% sales increase?")
X=retail_data[:,1]
Y=0.10*X
Z=retail_data[:,3]+retail_data[:,4]
print(Z)
Total_profit=(Y-Z)
print(Total_profit)
print("Total profit after change with 10% sales is",sum(Total_profit))


25. How will **total profit** change with the 10% sales increase?
[1210 1515 1108 1620 1412 1309 1718 1264 1825 1461]
[1290. 1685. 1692. 2480. 2088. 1391. 2182. 1736. 2675. 1839.]
Total profit after change with 10% sales is 19058.0


In [2]:
import numpy as np
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]

retail_data = np.array([
       [    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]
       ])
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [48]:
## Operational Strategy
print("26. Which stores need **inventory restocking** based on sales and current stock?")
X=retail_data[:,1]
Y=retail_data[:,3]
S=Y<(X*0.04)   #threshold concept
print(S)
Stores_to_restock=retail_data[S,0]
print("inventory restocking stores are",Stores_to_restock)



26. Which stores need **inventory restocking** based on sales and current stock?
[False False  True  True False False False False False False]
inventory restocking stores are [3 4]


In [33]:
print("27. Which stores show **high returns percentage** and might require **quality checks**?")
X=retail_data[:,2]
Y=retail_data[:,4]
R_percen=(Y/X)*100
print(R_percen)
S=retail_data[np.argmax(R_percen),0]
print("stores show **high returns percentage** and might require **quality checks** are",S)



27. Which stores show **high returns percentage** and might require **quality checks**?
[3.33333333 3.33333333 2.10526316 4.         2.85714286 2.5
 3.75       3.5        4.54545455 2.68292683]
stores show **high returns percentage** and might require **quality checks** are 9


In [12]:
print("28. Which store is the **best performer overall** (sales, customers, inventory turnover)?")
S=retail_data[:,1]
C=retail_data[:,2]
I=retail_data[:,3]
Inventory_turnover=S/I
A=((S/(S.max()))+(C/(C.max()))+(I/(I.max())))/3
print("**best performer overall** is",(np.argmax(A)+1))

28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
**best performer overall** is 9


In [13]:
print("29. Which store is the **worst performer overall**?")
S=retail_data[:,1]
C=retail_data[:,2]
I=retail_data[:,3]
Inventory_turnover=S/I
A=((S/(S.max()))+(C/(C.max()))+(I/(I.max())))/3
print("**best performer overall** is",(np.argmin(A)+1))



29. Which store is the **worst performer overall**?
**best performer overall** is 1


In [25]:

print("30. Which stores can be considered for **expansion** based on strong sales and customer metrics?")
S=np.mean(retail_data[:,1])
C=np.mean(retail_data[:,2])
E=retail_data[(retail_data[:,1]>S)&(retail_data[:,2]>C),0]
print("Stores consider for expansion",E)

30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
Stores consider for expansion [4 7 9]
