In [ ]:
Dataset Overview
The assignment uses banking industry data with 10 rows * 5 columns:
Customer_ID: Unique identifier for each customer
Account_Balance: Customer's account balance in dollars
Credit_Score: Customer's credit score (300-900 range)
Transaction_Count: Number of transactions in the last month
Years_Active: Number of years the customer has been with the bank")

In [ ]:
# Data – Banking Questions (for `data`)
**Assumed columns:** "[Customer ID, Account Balance, Credit score, Transaction Count, Years Active]"


In [2]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data.astype(int))

[[ 1001 12500   720    15     5]
 [ 1002  3450   610     8     2]
 [ 1003 78900   850    30    12]
 [ 1004   500   550     3     1]
 [ 1005 23000   780    22     8]
 [ 1006  1500   680    10     4]
 [ 1007 45000   800    25     9]
 [ 1008   750   490     5     1]
 [ 1009 62000   750    18     7]
 [ 1010  9000   660    12     3]]


In [12]:
#Question 1: Array Creation and Manipulation
print("Q1.1: Create a 4x4 identity matrix using np.eye()")
identity_matrix=np.eye(4)
print(identity_matrix)

Q1.1: Create a 4x4 identity matrix using np.eye()
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#Q2.2: Create an array of 8 zeros using np.zeros()
X=np.zeros(8)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#Q1.3: Create an array of 6 ones using np.ones()
X=np.ones(6)
print(X)

[1. 1. 1. 1. 1. 1.]


In [16]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
X=np.arange(0,16)
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [19]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
X=np.linspace(0,100,8)
print(X)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [34]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [31]:
# Question 2: Array Attributes and Information
# Q2.1: What is the shape of the banking_data array?
print(data.shape)

(10, 5)


In [30]:
# Q2.2: What is the data type of the banking_data array?
print(data.dtype)

float64


In [32]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
print(data.size)

50


In [37]:
# Q2.4: What is the number of dimensions of the banking_data array?
print(data.ndim)

2


In [38]:
# Q2.5: What is the memory size of the banking_data array in bytes?
print(data.nbytes)

400


In [ ]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

In [47]:
# Question 3: Indexing and Slicing
# Q3.1: Extract the first row of banking_data
first_row=data[0:1]
print(first_row)
print('$'*50)
print(first_row.astype(int))

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]]
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
[[ 1001 12500   720    15     5]]


In [55]:
# Q3.2: Extract the last row of banking_data
Last_row=data[9:10]
print(Last_row)
print(Last_row.astype(int))

[[1.01000e+03 9.00069e+03 6.60000e+02 1.20000e+01 3.00000e+00]]
[[1010 9000  660   12    3]]


In [56]:
# Q3.3: Extract the Account_Balance column (column index 1)
print(data[0:,1])

[12500.23  3450.1  78900.52   500.36 23000.68  1500.08 45000.31   750.01
 62000.75  9000.69]


In [78]:
# Q3.4: Extract the first 4 rows and first 3 columns
first_4_rows=data[0:5].astype(int)
first_3_columns=data[:,0:3].astype(int)
print("first four rows are",first_4_rows)
print("\nfirst three columns are", first_3_columns)

first four rows are [[ 1001 12500   720    15     5]
 [ 1002  3450   610     8     2]
 [ 1003 78900   850    30    12]
 [ 1004   500   550     3     1]
 [ 1005 23000   780    22     8]]

first three columns are [[ 1001 12500   720]
 [ 1002  3450   610]
 [ 1003 78900   850]
 [ 1004   500   550]
 [ 1005 23000   780]
 [ 1006  1500   680]
 [ 1007 45000   800]
 [ 1008   750   490]
 [ 1009 62000   750]
 [ 1010  9000   660]]


In [80]:
# Q3.5: Extract rows 3 to 7 (inclusive)
rows_3_to_7=data[2:7]
print(rows_3_to_7.astype(int))

[[ 1003 78900   850    30    12]
 [ 1004   500   550     3     1]
 [ 1005 23000   780    22     8]
 [ 1006  1500   680    10     4]
 [ 1007 45000   800    25     9]]


In [ ]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

In [83]:
# Question 4: Mathematical Operations
# Q4.1: Calculate the sum of all account balances
X=sum(data[0:,1])
print(X)

236603.73000000004


In [85]:
# Q4.2: Calculate the mean account balance
X=(data[0:,1]).mean()
print(X)

23660.373


In [87]:
# Q4.3: Calculate the standard deviation of account balances
X=np.std(data[0:,1])
print(X)

26976.927564263526


In [90]:
# Q4.4: Calculate the variance of account balances
X=np.var(data[0:,1])
print(X)

727754620.8075211


In [94]:
# Q4.5: Calculate the median account balance
X=np.median(data[0:,1])
print(X)

10750.46


In [95]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [100]:
# Question 5: Statistical Functions
# Q5.1: Find the minimum and maximum account balances
minimum_AB=np.min(data[0:,1])
print("min is ->",minimum_AB)
maximum_AB=np.max(data[0:,1])
print("max is->",maximum_AB)

min is -> 500.36
max is-> 78900.52


In [101]:
# Q5.2: Find the minimum and maximum credit scores
minimum_CS=np.min(data[0:,2])
print("min is ->",minimum_CS)
maximum_CS=np.max(data[0:,2])
print("max is->",maximum_CS)

min is -> 490.0
max is-> 850.0


In [104]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
per_25=np.percentile(data[0:,1],25)
print(per_25)
per_50=np.percentile(data[0:,1],50)
print(per_50)
print(np.median(data[0:,1])) #median=percentile_50
per_75=np.percentile(data[0:,1],75)
print(per_75)

1987.585
10750.46
10750.46
39500.4025


In [109]:
# Q5.4: Calculate the correlation between account balance and credit score
X=np.corrcoef((data[0:,1]),(data[0:,2]))[0,1]
print(X)

0.7939017490088559


In [114]:
# Q5.5: Calculate the covariance between account balance and credit score
X=np.cov((data[0:,1]),(data[0:,2]))[0,1]
print(X)

2577194.6922222227


In [115]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [117]:

# Question 6: Array Reshaping and Manipulation
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
X=data.reshape(5,10)
print(X.astype(int))

[[ 1001 12500   720    15     5  1002  3450   610     8     2]
 [ 1003 78900   850    30    12  1004   500   550     3     1]
 [ 1005 23000   780    22     8  1006  1500   680    10     4]
 [ 1007 45000   800    25     9  1008   750   490     5     1]
 [ 1009 62000   750    18     7  1010  9000   660    12     3]]


In [119]:
# Q6.2: Flatten the banking_data to a 1D array
X=data.flatten()
print(X.astype(int))

[ 1001 12500   720    15     5  1002  3450   610     8     2  1003 78900
   850    30    12  1004   500   550     3     1  1005 23000   780    22
     8  1006  1500   680    10     4  1007 45000   800    25     9  1008
   750   490     5     1  1009 62000   750    18     7  1010  9000   660
    12     3]


In [122]:
# Q6.3: Transpose the banking_data
X=data.T
print(X.astype(int))

[[ 1001  1002  1003  1004  1005  1006  1007  1008  1009  1010]
 [12500  3450 78900   500 23000  1500 45000   750 62000  9000]
 [  720   610   850   550   780   680   800   490   750   660]
 [   15     8    30     3    22    10    25     5    18    12]
 [    5     2    12     1     8     4     9     1     7     3]]


In [131]:
# Q6.4: Split the banking_data into 2 equal parts vertically
X=np.split(data,2)
part1=X[0]
part2=X[1]
print(part1.astype(int))
print(part2.astype(int))

[[ 1001 12500   720    15     5]
 [ 1002  3450   610     8     2]
 [ 1003 78900   850    30    12]
 [ 1004   500   550     3     1]
 [ 1005 23000   780    22     8]]
[[ 1006  1500   680    10     4]
 [ 1007 45000   800    25     9]
 [ 1008   750   490     5     1]
 [ 1009 62000   750    18     7]
 [ 1010  9000   660    12     3]]


In [148]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
X=np.array_split(data,2, axis=1)
part1=X[0]
part2=X[1]
print(part1.astype(int))
print(part2.astype(int))

[[ 1001 12500   720]
 [ 1002  3450   610]
 [ 1003 78900   850]
 [ 1004   500   550]
 [ 1005 23000   780]
 [ 1006  1500   680]
 [ 1007 45000   800]
 [ 1008   750   490]
 [ 1009 62000   750]
 [ 1010  9000   660]]
[[15  5]
 [ 8  2]
 [30 12]
 [ 3  1]
 [22  8]
 [10  4]
 [25  9]
 [ 5  1]
 [18  7]
 [12  3]]


In [ ]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [151]:

# Question 7: Logical Operations and Filtering
# Q7.1: Find customers with account balance greater than $100,000
X=data[0:,1]>100000
print(X)

[False False False False False False False False False False]


In [164]:
# Q7.2: Find customers with credit score greater than 800
X=data[data[0:,2]>800][:,0]
print(X.astype(int))

[1003]


In [184]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  150,  5],
       [    1002,  3450.10, 610,   80,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   300,  1],
       [    1005, 23000.68, 780,  220,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   50,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+02 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+01 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+02 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+02 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+01 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [ ]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
X=data[(data[:,3]>50) & (data[:,2]<750)][:,0]
print(X)


[1001. 1002. 1004.]


In [203]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
X=data[((data[0:,1])>10000) & ((data[0:,1])<100000)][:,0]
print(X)
print(X.shape)

[1001. 1003. 1005. 1007. 1009.]
(5,)


In [205]:
# Q7.5: Find the index of the customer with the highest credit score
X=np.argmax(data[0:,3])
print(X)

3


In [ ]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [208]:

# Question 8: Sorting and Searching
# Q8.1: Sort the banking_data by account balance (ascending)
X=data[data[0:,1].argsort()]
print(X.astype(int))

[[ 1004   500   550     3     1]
 [ 1008   750   490     5     1]
 [ 1006  1500   680    10     4]
 [ 1002  3450   610     8     2]
 [ 1010  9000   660    12     3]
 [ 1001 12500   720    15     5]
 [ 1005 23000   780    22     8]
 [ 1007 45000   800    25     9]
 [ 1009 62000   750    18     7]
 [ 1003 78900   850    30    12]]


In [209]:
# Q8.2: Sort the banking_data by credit score (descending)
X=data[data[0:,2].argsort()]
print(X.astype(int))

[[ 1008   750   490     5     1]
 [ 1004   500   550     3     1]
 [ 1002  3450   610     8     2]
 [ 1010  9000   660    12     3]
 [ 1006  1500   680    10     4]
 [ 1001 12500   720    15     5]
 [ 1009 62000   750    18     7]
 [ 1005 23000   780    22     8]
 [ 1007 45000   800    25     9]
 [ 1003 78900   850    30    12]]


In [223]:
# Q8.3: Find the indices that would sort the array by years active
X=data[data[:,4].argsort()]
print(X.astype(int))

[[ 1004   500   550     3     1]
 [ 1008   750   490     5     1]
 [ 1002  3450   610     8     2]
 [ 1010  9000   660    12     3]
 [ 1006  1500   680    10     4]
 [ 1001 12500   720    15     5]
 [ 1009 62000   750    18     7]
 [ 1005 23000   780    22     8]
 [ 1007 45000   800    25     9]
 [ 1003 78900   850    30    12]]


In [246]:
# Q8.4: Find the customer with the second highest account balance
X=data[data[:,1].argsort()]
print(X.astype(int))
print((f"the customer with 2nd highest AB is ->",(X[-2][0].astype(int))))

[[ 1004   500   550     3     1]
 [ 1008   750   490     5     1]
 [ 1006  1500   680    10     4]
 [ 1002  3450   610     8     2]
 [ 1010  9000   660    12     3]
 [ 1001 12500   720    15     5]
 [ 1005 23000   780    22     8]
 [ 1007 45000   800    25     9]
 [ 1009 62000   750    18     7]
 [ 1003 78900   850    30    12]]
('the customer with 2nd highest AB is ->', np.int64(1009))


In [252]:
# Q8.5: Find the customer with the lowest transaction count
X=np.argmin(data[0:,3])
print(X)

3


In [253]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [ ]:

# Question 9: Mathematical Functions
# Q9.1: Calculate the absolute values of all elements
X=np.abs(data)
print(X)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [255]:
# Q9.2: Calculate the square root of all account balances
X=np.sqrt(data[0:,1])
print(X)

[111.80442746  58.73755187 280.89236373  22.36872817 151.65975076
  38.73086624 212.13276503  27.38631045 248.99949799  94.87196635]


In [256]:
# Q9.3: Calculate the square of all credit scores
X=np.square(data[0:,2])
print(X)

[518400. 372100. 722500. 302500. 608400. 462400. 640000. 240100. 562500.
 435600.]


In [257]:
# Q9.4: Calculate the exponential of all transaction counts
X=np.exp(data[0:,3])
print(X)

[3.26901737e+06 2.98095799e+03 1.06864746e+13 2.00855369e+01
 3.58491285e+09 2.20264658e+04 7.20048993e+10 1.48413159e+02
 6.56599691e+07 1.62754791e+05]


In [258]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [265]:
# Question 10: Advanced Operations
# Q10.1: Calculate the cumulative sum of account balances
X=np.cumsum(data[0:,1])
print(X)

[ 12500.23  15950.33  94850.85  95351.21 118351.89 119851.97 164852.28
 165602.29 227603.04 236603.73]


In [ ]:
# Q10.2: Calculate the cumulative product of transaction counts
X=np.cumprod(data[0:,3])
print(X)

[1.5000e+01 1.2000e+02 3.6000e+03 1.0800e+04 2.3760e+05 2.3760e+06
 5.9400e+07 2.9700e+08 5.3460e+09 6.4152e+10]


In [267]:
# Q10.3: Calculate the difference between consecutive account balances
X=np.diff(data[0:,1])
print(X)

[ -9050.13  75450.42 -78400.16  22500.32 -21500.6   43500.23 -44250.3
  61250.74 -53000.06]


In [268]:
# Q10.4: Calculate the gradient of account balances
X=np.gradient(data[0:,1])
print(X)

[ -9050.13   33200.145  -1474.87  -27949.92     499.86   10999.815
   -375.035   8500.22    4125.34  -53000.06 ]


In [270]:
# Q10.5: Calculate the histogram of account balances with 5 bins
X=np.histogram(data[0:,1],bins=5)
print(X)

(array([6, 1, 1, 1, 1]), array([  500.36 , 16180.392, 31860.424, 47540.456, 63220.488, 78900.52 ]))


In [271]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [273]:
# Question 11: Random Numbers and Simulation
# Q11.1: Generate 6 random integers between 1 and 1000
import numpy as np
R_I=np.random.randint(1,100,6)
print(R_I)

[41 88 94 83 88 91]


In [276]:
# Q11.2: Generate 6 random floats between 0 and 1
import numpy as np
R_F=np.random.rand(6)
print(R_F)

[0.15317521 0.92041517 0.55926339 0.23813778 0.85839439 0.28267245]


In [278]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
import numpy as np
R_N=np.random.normal(700,100,6)
print(R_N)

[747.90014371 777.344442   806.90972229 765.41668509 542.5854934
 758.13078889]


In [281]:
# Q11.4: Shuffle the banking_data rows randomly
import numpy as np
S=np.random.shuffle(data)
print(data.astype(int))

[[ 1007 45000   800    25     9]
 [ 1005 23000   780    22     8]
 [ 1004   500   550     3     1]
 [ 1003 78900   850    30    12]
 [ 1010  9000   660    12     3]
 [ 1009 62000   750    18     7]
 [ 1002  3450   610     8     2]
 [ 1001 12500   720    15     5]
 [ 1006  1500   680    10     4]
 [ 1008   750   490     5     1]]


In [282]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
R_N=np.random.rand(4)
print(R_N)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [259]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [284]:
# Question 12: Linear Algebra Operations
# Q12.1: Calculate the dot product of account balance and credit score columns
X=np.dot((data[0:,1]),(data[0:,2]))
print(X)

186214722.2


In [285]:
# Q12.2: Calculate the cross product of first two rows
X=np.cross(data[0,:3],data[1,:3])
print(X)

[ 1.66996978e+07  1.85400000e+04 -2.20636268e+07]


In [286]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
X=np.linalg.norm(data[0:,1])
print(X)

113471.04790679648


In [289]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix=np.array([
    [2, 5, 8],
    [9, 4, 7],
    [0, 6, 1]
])
Det=np.linalg.det(matrix)
print(Det)

311.0000000000002


In [ ]:
# Q12.5: Calculate the inverse of the 3x3 matrix

In [291]:

inverse=np.linalg.inv(matrix)
print(inverse)

[[-0.1221865   0.13826367  0.0096463 ]
 [-0.02893891  0.00643087  0.18649518]
 [ 0.17363344 -0.03858521 -0.11897106]]


In [295]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    101, 12500.23, 720,  15,  5],
       [    102,  3450.10, 610,   8,  2],
       [    103, 78900.52, 850,  30, 12],
       [    104,   500.36, 550,   3,  1],
       [    105, 23000.68, 780,  22,  8],
       [    106,  1500.08, 680,  10,  4],
       [    107, 45000.31, 800,  25,  9],
       [    108,   750.01, 490,   5,  1],
       [    109, 62000.75, 750,  18,  7],
       [    100,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.010000e+02 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.020000e+02 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.030000e+02 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.040000e+02 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.050000e+02 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.060000e+02 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.070000e+02 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.080000e+02 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.090000e+02 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.000000e+02 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [306]:
#  Question 13: String Operations
# Q13.1: Convert all customer IDs to strings
X=data[0:,0].astype(str)
print(X)

['101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0' '108.0' '109.0'
 '100.0']


In [327]:
# Q13.2: Check if any customer ID contains '100'
X=data[0:,0].astype(str)
Y=np.where(X=='100.0')[0]
print(X)
print(Y)

['101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0' '108.0' '109.0'
 '100.0']
[9]


In [317]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
X=data[0:,0].astype(str)
print(X)
Y=np.char.upper(X)
print(Y)

['101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0' '108.0' '109.0'
 '100.0']
['101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0' '108.0' '109.0'
 '100.0']


In [324]:
# Q13.4: Count the length of each customer ID string
X=data[0:,0].astype(str)
Y=np.char.str_len(X)
print(Y)

[5 5 5 5 5 5 5 5 5 5]


In [326]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
X=data[0:,0].astype(str)
Y=np.where(X=='100.0','CUST',X)
print(Y)

['101.0' '102.0' '103.0' '104.0' '105.0' '106.0' '107.0' '108.0' '109.0'
 'CUST']


In [1]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [2]:
# Question 14: Date and Time Operations
# Q14.1: Convert years active to months
X=data[0:,4]*12
print(X)

[ 60.  24. 144.  12.  96.  48. 108.  12.  84.  36.]


In [3]:
# Q14.2: Calculate the average years active
X=data[0:,4].mean()
print(X)

5.2


In [6]:
# Q14.3: Find customers who have been active for more than 5 years
X=data[(data[0:,4])>5][:,0]
print(X.astype(int))

[1003 1005 1007 1009]


In [9]:
# Q14.4: Calculate the total time all customers have been active (in years)
X=sum(data[0:,4])
print(X)

52.0


In [10]:
# Q14.5: Find the customer with the shortest time active
X=np.argmin(data[0:,4])
print(X)

3


In [262]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [11]:
# Question 15: Advanced Array Operations
# Q15.1: Apply a function to calculate 5% interest on all account balances
X=(data[0:,1]*(5/100))
print(X)

[ 625.0115  172.505  3945.026    25.018  1150.034    75.004  2250.0155
   37.5005 3100.0375  450.0345]


In [21]:
# Q15.2: Use np.where to categorize customers by balance ranges
X=(data[0:,1])
print(X)
Y=np.where(X<5000,'Low',
  np.where((X>=5000)&(X<10000),'Medium','High'))
print(Y)

[12500.23  3450.1  78900.52   500.36 23000.68  1500.08 45000.31   750.01
 62000.75  9000.69]
['High' 'Low' 'High' 'Low' 'High' 'Low' 'High' 'Low' 'High' 'Medium']


In [28]:
# Q15.3: Use np.select to categorize customers by credit score ranges
X=data[0:,2]
print(X)
Y=[ (X<650),
    (X>=650)&(X<700),
    (X>=700)&(X<740),
    (X>=740)&(X<800),
    (X>=800)]   
Z=['Poor','Fair','Good','Very Good','Excellent' ]
Categorize=np.select(Y,Z,default='unknown')
print(Categorize)

[720. 610. 850. 550. 780. 680. 800. 490. 750. 660.]
['Good' 'Poor' 'Excellent' 'Poor' 'Very Good' 'Fair' 'Excellent' 'Poor'
 'Very Good' 'Fair']


In [29]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
X=data[0:,1]
print(X)
Y=[(X<5000),
  (X>=5000)&(X<10000),
  (X>=10000)]
Z=[2/100,
   3.5/100,
   5/100]
I_R=np.piecewise(X,Y,Z)
print(I_R)

[12500.23  3450.1  78900.52   500.36 23000.68  1500.08 45000.31   750.01
 62000.75  9000.69]
[0.05  0.02  0.05  0.02  0.05  0.02  0.05  0.02  0.05  0.035]


In [33]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
print(data.astype(int))
X=np.apply_along_axis(np.sum,axis=1,arr=data)
print(X.astype(int))

[[ 1001 12500   720    15     5]
 [ 1002  3450   610     8     2]
 [ 1003 78900   850    30    12]
 [ 1004   500   550     3     1]
 [ 1005 23000   780    22     8]
 [ 1006  1500   680    10     4]
 [ 1007 45000   800    25     9]
 [ 1008   750   490     5     1]
 [ 1009 62000   750    18     7]
 [ 1010  9000   660    12     3]]
[14241  5072 80795  2058 24815  3200 46841  2254 63784 10685]


In [34]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)


[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [39]:
# Question 16: Array Concatenation and Stacking
# Q16.1: Concatenate two arrays horizontally using np.hstack()
X=np.hstack(data)
print(X.astype(int))

[ 1001 12500   720    15     5  1002  3450   610     8     2  1003 78900
   850    30    12  1004   500   550     3     1  1005 23000   780    22
     8  1006  1500   680    10     4  1007 45000   800    25     9  1008
   750   490     5     1  1009 62000   750    18     7  1010  9000   660
    12     3]


In [40]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
Y=np.vstack(X)
print(Y.astype(int))

[[ 1001]
 [12500]
 [  720]
 [   15]
 [    5]
 [ 1002]
 [ 3450]
 [  610]
 [    8]
 [    2]
 [ 1003]
 [78900]
 [  850]
 [   30]
 [   12]
 [ 1004]
 [  500]
 [  550]
 [    3]
 [    1]
 [ 1005]
 [23000]
 [  780]
 [   22]
 [    8]
 [ 1006]
 [ 1500]
 [  680]
 [   10]
 [    4]
 [ 1007]
 [45000]
 [  800]
 [   25]
 [    9]
 [ 1008]
 [  750]
 [  490]
 [    5]
 [    1]
 [ 1009]
 [62000]
 [  750]
 [   18]
 [    7]
 [ 1010]
 [ 9000]
 [  660]
 [   12]
 [    3]]


In [51]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
X=np.random.randint(0,4,10)
print(X)
Y=np.random.randint(0,4,10)
print(Y)
Z=np.concatenate((X,Y), axis=0)
print(Z)

[1 2 2 3 0 0 3 0 3 3]
[0 3 0 3 3 3 1 2 1 0]
[1 2 2 3 0 0 3 0 3 3 0 3 0 3 3 3 1 2 1 0]


In [55]:
# Q16.4: Stack arrays depth-wise using np.dstack()
Z=np.dstack((X,Y))
print(Z)

[[[1 0]
  [2 3]
  [2 0]
  [3 3]
  [0 3]
  [0 3]
  [3 1]
  [0 2]
  [3 1]
  [3 0]]]


In [59]:
# Q16.5: Create a column stack using np.column_stack()
X=np.random.randint(2,4,10)
print(X)
Y=np.random.randint(2,4,10)
print(Y)
Z=np.column_stack((X,Y))
print(Z)

[2 2 3 2 2 2 2 3 2 2]
[3 3 3 3 3 2 2 2 2 3]
[[2 3]
 [2 3]
 [3 3]
 [2 3]
 [2 3]
 [2 2]
 [2 2]
 [3 2]
 [2 2]
 [2 3]]


In [263]:
import numpy as np
# Manually created array: [Customer ID, Account Balance, Credit score, Transaction Count, Years Active]
data=np.array([
       [    1001, 12500.23, 720,  15,  5],
       [    1002,  3450.10, 610,   8,  2],
       [    1003, 78900.52, 850,  30, 12],
       [    1004,   500.36, 550,   3,  1],
       [    1005, 23000.68, 780,  22,  8],
       [    1006,  1500.08, 680,  10,  4],
       [    1007, 45000.31, 800,  25,  9],
       [    1008,   750.01, 490,   5,  1],
       [    1009, 62000.75, 750,  18,  7],
       [    1010,  9000.69, 660,  12,  3]
       ])
print(data)

[[1.001000e+03 1.250023e+04 7.200000e+02 1.500000e+01 5.000000e+00]
 [1.002000e+03 3.450100e+03 6.100000e+02 8.000000e+00 2.000000e+00]
 [1.003000e+03 7.890052e+04 8.500000e+02 3.000000e+01 1.200000e+01]
 [1.004000e+03 5.003600e+02 5.500000e+02 3.000000e+00 1.000000e+00]
 [1.005000e+03 2.300068e+04 7.800000e+02 2.200000e+01 8.000000e+00]
 [1.006000e+03 1.500080e+03 6.800000e+02 1.000000e+01 4.000000e+00]
 [1.007000e+03 4.500031e+04 8.000000e+02 2.500000e+01 9.000000e+00]
 [1.008000e+03 7.500100e+02 4.900000e+02 5.000000e+00 1.000000e+00]
 [1.009000e+03 6.200075e+04 7.500000e+02 1.800000e+01 7.000000e+00]
 [1.010000e+03 9.000690e+03 6.600000e+02 1.200000e+01 3.000000e+00]]


In [73]:
# Question 17: Array Splitting Operations
# Q17.1: Split an array into 3 equal parts using np.split()
X=np.random.randint(10,18,9)
print(X)
Y=np.split(X,3)
print(Y)

[12 11 17 13 12 12 17 11 14]
[array([12, 11, 17], dtype=int32), array([13, 12, 12], dtype=int32), array([17, 11, 14], dtype=int32)]


In [74]:
# Q17.2: Split an array at specific indices using np.split()
X=np.random.randint(10,18,9)
print(X)
Y=np.split(X,[2,5])
print(Y)

[14 17 14 14 17 12 17 13 17]
[array([14, 17], dtype=int32), array([14, 14, 17], dtype=int32), array([12, 17, 13, 17], dtype=int32)]


In [87]:
# Q17.3: Split an array horizontally using np.hsplit()
X=np.random.randint(10,18,(10,5))
print(X)
print('%'*100)
Y=np.hsplit(X,[2,4])
print("\n",Y)

[[13 16 16 13 10]
 [12 11 10 11 10]
 [16 15 12 15 15]
 [14 15 10 17 12]
 [10 13 14 16 16]
 [12 10 12 16 17]
 [15 11 15 14 16]
 [14 16 16 15 14]
 [10 17 13 10 15]
 [13 11 11 12 16]]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

 [array([[13, 16],
       [12, 11],
       [16, 15],
       [14, 15],
       [10, 13],
       [12, 10],
       [15, 11],
       [14, 16],
       [10, 17],
       [13, 11]], dtype=int32), array([[16, 13],
       [10, 11],
       [12, 15],
       [10, 17],
       [14, 16],
       [12, 16],
       [15, 14],
       [16, 15],
       [13, 10],
       [11, 12]], dtype=int32), array([[10],
       [10],
       [15],
       [12],
       [16],
       [17],
       [16],
       [14],
       [15],
       [16]], dtype=int32)]


In [ ]:
# Q17.4: Split an array vertically using np.vsplit()
X=np.random.randint(10,18,(10,5))
print(X)
Y=np.vsplit(X,[2,5])
print("\n",Y)

[[11 11 17 14 10]
 [11 12 17 10 12]
 [17 17 14 11 12]
 [12 16 11 13 15]
 [10 17 13 17 13]
 [10 11 14 14 15]
 [12 12 16 11 14]
 [13 17 11 13 14]
 [16 13 15 11 14]
 [13 13 11 11 14]]

 [array([[11, 11, 17, 14, 10],
       [11, 12, 17, 10, 12]], dtype=int32), array([[17, 17, 14, 11, 12],
       [12, 16, 11, 13, 15],
       [10, 17, 13, 17, 13]], dtype=int32), array([[10, 11, 14, 14, 15],
       [12, 12, 16, 11, 14],
       [13, 17, 11, 13, 14],
       [16, 13, 15, 11, 14],
       [13, 13, 11, 11, 14]], dtype=int32)]


In [106]:
# Q17.5: Split an array into equal chunks using np.array_split()
X=np.random.randint(10,18,(10,10))
print(X)
Y=np.array_split(X,7)
print(Y)
for i,chunk in enumerate(Y):
    print(f"chunk {i+1}:")
    print(chunk)

[[11 10 17 12 13 14 11 13 12 17]
 [17 13 11 11 12 14 17 13 11 10]
 [11 16 14 10 15 13 10 10 13 13]
 [12 13 16 17 16 16 14 15 15 11]
 [14 17 11 16 12 15 13 10 17 17]
 [11 12 13 13 12 15 16 13 16 10]
 [12 13 12 15 10 14 13 10 17 15]
 [11 14 13 15 11 13 16 15 14 12]
 [16 16 11 16 12 16 15 12 16 15]
 [15 11 12 14 13 17 10 16 14 17]]
[array([[11, 10, 17, 12, 13, 14, 11, 13, 12, 17],
       [17, 13, 11, 11, 12, 14, 17, 13, 11, 10]], dtype=int32), array([[11, 16, 14, 10, 15, 13, 10, 10, 13, 13],
       [12, 13, 16, 17, 16, 16, 14, 15, 15, 11]], dtype=int32), array([[14, 17, 11, 16, 12, 15, 13, 10, 17, 17],
       [11, 12, 13, 13, 12, 15, 16, 13, 16, 10]], dtype=int32), array([[12, 13, 12, 15, 10, 14, 13, 10, 17, 15]], dtype=int32), array([[11, 14, 13, 15, 11, 13, 16, 15, 14, 12]], dtype=int32), array([[16, 16, 11, 16, 12, 16, 15, 12, 16, 15]], dtype=int32), array([[15, 11, 12, 14, 13, 17, 10, 16, 14, 17]], dtype=int32)]
chunk 1:
[[11 10 17 12 13 14 11 13 12 17]
 [17 13 11 11 12 14 17 13 11 10

In [108]:
# Question 18: Array Repetition and Tiling
# Q18.1: Repeat each element of an array 3 times using np.repeat()
X=np.random.randint(10,18,10)
print(X)
Y=np.repeat(X,3)
print(Y)

[12 14 17 13 15 10 13 17 11 17]
[12 12 12 14 14 14 17 17 17 13 13 13 15 15 15 10 10 10 13 13 13 17 17 17
 11 11 11 17 17 17]


In [110]:
# Q18.2: Repeat an entire array 2 times using np.tile()
X=np.random.randint(10,18,10)
print(X)
Y=np.tile(X,2)
print("\n",Y)

[10 14 14 14 11 17 10 16 12 10]

 [10 14 14 14 11 17 10 16 12 10 10 14 14 14 11 17 10 16 12 10]


In [113]:
# Q18.3: Repeat a 2D array using np.tile()
X=np.random.randint(10,18,4)
print(X)
Y=np.tile(X,(2,3))
print(Y)

[15 17 10 13]
[[15 17 10 13 15 17 10 13 15 17 10 13]
 [15 17 10 13 15 17 10 13 15 17 10 13]]


In [115]:
# Q18.4: Create a pattern using np.tile()
X=np.tile(data,(2,3))
print(X.astype(int))

[[ 1001 12500   720    15     5  1001 12500   720    15     5  1001 12500
    720    15     5]
 [ 1002  3450   610     8     2  1002  3450   610     8     2  1002  3450
    610     8     2]
 [ 1003 78900   850    30    12  1003 78900   850    30    12  1003 78900
    850    30    12]
 [ 1004   500   550     3     1  1004   500   550     3     1  1004   500
    550     3     1]
 [ 1005 23000   780    22     8  1005 23000   780    22     8  1005 23000
    780    22     8]
 [ 1006  1500   680    10     4  1006  1500   680    10     4  1006  1500
    680    10     4]
 [ 1007 45000   800    25     9  1007 45000   800    25     9  1007 45000
    800    25     9]
 [ 1008   750   490     5     1  1008   750   490     5     1  1008   750
    490     5     1]
 [ 1009 62000   750    18     7  1009 62000   750    18     7  1009 62000
    750    18     7]
 [ 1010  9000   660    12     3  1010  9000   660    12     3  1010  9000
    660    12     3]
 [ 1001 12500   720    15     5  1001 12500   720 

In [120]:
# Q18.5: Repeat elements with different counts using np.repeat()
X=np.random.randint(10,18,4)
print(X)
Y=[2,3,4,5]
Z=np.repeat(X,Y)
print(Z)

[10 14 16 14]
[10 10 14 14 14 16 16 16 16 14 14 14 14 14]


In [ ]:

# Question 19: Array Comparison and Logical Operations
# Q19.1: Compare two arrays for equality using np.array_equal()
X=np.array([[1,2,3],[4,5,6]])
Y=np.array([[1,2,3],[4,5,6]])
Z=np.array_equal(X,Y)
print(Z)

True


In [132]:
# Q19.2: Check if arrays are close using np.allclose()
X=np.array([[1.00001,2.00005,3.00006,4.00007]])
Y=np.array([[1.00002,2.00007,3.00001,4.00002]])
Z=np.allclose(X,Y)
print(Z)

False


In [134]:
X=np.array([[1.00001,2.00005,3.00006,4.00007]])
Y=np.array([[1.00002,2.00006,3.00005,4.00006]])
Z=np.allclose(X,Y)
print(Z)

True


In [141]:
# Q19.3: Apply logical AND operation between arrays
X=np.array([1,0,1,0,1,0])
Y=np.array([0,1,1,0,2,1])
Z=np.logical_and(X,Y)
print(Z)

[False False  True False  True False]


In [142]:
# Q19.4: Apply logical OR operation between arrays
X=np.array([1,0,1,0,1,0])
Y=np.array([0,1,1,0,2,1])
Z=np.logical_or(X,Y)
print(Z)

[ True  True  True False  True  True]


In [ ]:
# Q19.5: Apply logical NOT operation to an array
X=np.array([1,0,1,0,1,0])
Z=np.logical_not(X)
print(Z)

[False  True False  True False  True]


In [150]:
print(data.astype(int))

[[ 1001 12500   720    15     5]
 [ 1002  3450   610     8     2]
 [ 1003 78900   850    30    12]
 [ 1004   500   550     3     1]
 [ 1005 23000   780    22     8]
 [ 1006  1500   680    10     4]
 [ 1007 45000   800    25     9]
 [ 1008   750   490     5     1]
 [ 1009 62000   750    18     7]
 [ 1010  9000   660    12     3]]


In [152]:
# Question 20: Array Set Operations
# Q20.1: Find unique elements in an array using np.unique()
X=np.unique(data)
print(X.astype(int))

[    1     2     3     4     5     7     8     9    10    12    15    18
    22    25    30   490   500   550   610   660   680   720   750   750
   780   800   850  1001  1002  1003  1004  1005  1006  1007  1008  1009
  1010  1500  3450  9000 12500 23000 45000 62000 78900]


In [154]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
X=np.array([1,0,1,0,1,0])
Y=np.array([0,1,1,0,2,1])
Z=np.intersect1d(X,Y)
print(Z)

[0 1]


In [155]:
# Q20.3: Find the union of two arrays using np.union1d()
X=np.array([1,0,1,0,1,0])
Y=np.array([0,1,1,0,2,1])
Z=np.union1d(X,Y)
print(Z)

[0 1 2]


In [158]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
X=np.array([1,0,6,2,3,5,1])
Y=np.array([3,4,1,2,0,1,0])
Z=np.setdiff1d(X,Y)
print(Z)

[5 6]


In [159]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
X=np.array([1,0,6,2,3,5,1])
Y=np.array([3,4,1,2,0,1,0])
Z=np.setxor1d(X,Y)
print(Z)

[4 5 6]
